version: '3.8'

services:
  router:
    build: ./router-server
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./config.json:/app/config.json
    depends_on:
      - search
      - think
      - weather
      - rag
      - redis

  search:
    build: ./search-server
    ports:
      - "8002:8002"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}

  think:
    build: ./think-server
    ports:
      - "8003:8003"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}

  weather:
    build: ./weather-server
    ports:
      - "8005:8005"
    environment:
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}

  rag:
    build: ./rag-server
    ports:
      - "8004:8004"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
